/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by
 * Xamarin.Android from the resource data it found.
 * It should not be modified by hand.
 */
package androidx.drawerlayout;

public final class R {
	public static final class attr {
		public static final int drawerLayoutStyle = 0x7f030078;
		public static final int elevation = 0x7f03007e;
	}
	public static final class dimen {
		public static final int def_drawer_elevation = 0x7f060058;
	}
	public static final class styleable {
		public static final int[] DrawerLayout = new int[] { 0x7f03007e };
		public static final int DrawerLayout_elevation = 0;
	}
}
