/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by
 * Xamarin.Android from the resource data it found.
 * It should not be modified by hand.
 */
package androidx.core.splashscreen;

public final class R {
	public static final class attr {
		public static final int postSplashScreenTheme = 0x7f0300c6;
		public static final int splashScreenIconSize = 0x7f0300e0;
		public static final int windowSplashScreenAnimatedIcon = 0x7f030124;
		public static final int windowSplashScreenAnimationDuration = 0x7f030125;
		public static final int windowSplashScreenBackground = 0x7f030126;
		public static final int windowSplashScreenIconBackgroundColor = 0x7f030127;
	}
	public static final class dimen {
		public static final int splashscreen_icon_mask_size_no_background = 0x7f060071;
		public static final int splashscreen_icon_mask_size_with_background = 0x7f060072;
		public static final int splashscreen_icon_mask_stroke_no_background = 0x7f060073;
		public static final int splashscreen_icon_mask_stroke_with_background = 0x7f060074;
		public static final int splashscreen_icon_size = 0x7f060075;
		public static final int splashscreen_icon_size_no_background = 0x7f060076;
		public static final int splashscreen_icon_size_with_background = 0x7f060077;
	}
	public static final class drawable {
		public static final int compat_splash_screen = 0x7f07005c;
		public static final int compat_splash_screen_no_icon_background = 0x7f07005d;
		public static final int icon_background = 0x7f070065;
	}
	public static final class id {
		public static final int splashscreen_icon_view = 0x7f08008b;
	}
	public static final class integer {
		public static final int default_icon_animation_duration = 0x7f090004;
	}
	public static final class layout {
		public static final int splash_screen_view = 0x7f0b0028;
	}
	public static final class style {
		public static final int Base_Theme_SplashScreen = 0x7f0d004a;
		public static final int Base_Theme_SplashScreen_DayNight = 0x7f0d004b;
		public static final int Base_Theme_SplashScreen_Light = 0x7f0d004c;
		public static final int Base_v21_Theme_SplashScreen = 0x7f0d00a4;
		public static final int Base_v21_Theme_SplashScreen_Light = 0x7f0d00a5;
		public static final int Base_v27_Theme_SplashScreen = 0x7f0d00a6;
		public static final int Base_v27_Theme_SplashScreen_Light = 0x7f0d00a7;
		public static final int Theme_SplashScreen = 0x7f0d0114;
		public static final int Theme_SplashScreen_Common = 0x7f0d0115;
		public static final int Theme_SplashScreen_IconBackground = 0x7f0d0116;
	}
}
